[package]
name = "lycan-serialize"
version = "0.1.0"
authors = ["Vaelden <maugan.villatel@gmail.com>"]
build = "build.rs"

[build-dependencies]
capnpc = "*"

[dependencies]
capnp = "*"
log = "*"
byteorder = "*"

[features]
# Use JSON as serialization format instead of CapnProto
json = ["rustc-serialize"]

[dependencies.rustc-serialize]
version = "*"
optional = true
